version: '3.8'

services:
  vicsam-api:
    # Usa l'immagine dal GitHub Container Registry
    image: ghcr.io/berry-13/vicsam-group:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-your-production-jwt-secret-here}
      - BEARER_TOKEN=${BEARER_TOKEN:-your-production-bearer-token-here}
      - API_PASSWORD=${API_PASSWORD:-your-production-password-here}
    volumes:
      - ./data:/app/data  # Persistenza dati
      - ./logs:/app/logs  # Persistenza log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - vicsam-network

networks:
  vicsam-network:
    driver: bridge

volumes:
  vicsam-data:
    driver: local
  vicsam-logs:
    driver: local
