version: '3.8'

services:
  vicsam-api-dev:
    build: 
      context: .
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped
    
  # Database per sviluppo (opzionale)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=vicsam_dev
      - POSTGRES_USER=vicsam
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis per caching (opzionale)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
