version: '3.8'

services:
  vicsam-api:
    # For production: use prebuilt image from GitHub Container Registry
    # image: ghcr.io/berry-13/vicsam-group:latest
    # For development: build locally
    build: 
      context: .
      target: production
      cache_from:
        - node:20-alpine
        - ghcr.io/berry-13/vicsam-group:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-your-production-jwt-secret-here}
      - BEARER_TOKEN=${BEARER_TOKEN:-your-production-bearer-token-here}
      - API_PASSWORD=${API_PASSWORD:-your-production-password-here}
    volumes:
      - data:/app/data
      - logs:/app/logs
    restart: unless-stopped
    networks:
      - vicsam-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 60s
      timeout: 10s
      retries: 2
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
  
  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      vicsam-api:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - vicsam-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

# Development override
  vicsam-dev:
    profiles: ["dev"]
    build:
      target: base
      context: .
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - "3000:3000"
      - "5173:5173"  # Vite dev server
    networks:
      - vicsam-network

volumes:
  data:
    driver: local
  logs:
    driver: local

networks:
  vicsam-network:
    driver: bridge
